spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQC28w/vFEG15u9dgbWi/Z8jewz/NlWK3xzNMKu29xAqh4pOrRmRED5IkwoWHBDxE2RY+lgcgekynnckh5q0ipHpl1X9uQK42xxf1WGq0D56DgmQhvnlAFiqaKJR4YKXJQHvw+1aJaLgzBJl0m4bM7HDO5aRIgUPD39fsy0C0KVCdUxu4NZzLdyRjjMtjCL+kweNv6pqERbpW9TqpbyTPJalcn6iMGgsP7U0HNhlExCt/z0mn6O9AgRoV41zHdkDU/zA91wTjyoONUu83DfmPjJVkP6Mi3iEtMbjBohvf9/j1TiAUQF21yPNJYenGDP1KWph0mKuZF2fO9o0bbT20qUdv59v9XsTbcW86hefDasIqVBXq9gtCIxYCTaEvpWaccI='

# JWT 관련 환경 변수
jwt:
    secret: 1ba112e536012abca2dd7849949ec353599feb1c5c5615c1aa3bda5456bb30a513b1aed725c568d4e42407434d9c6bf69d4655d331c3495c052c8195af2340fc
    expiration:
        access: 86400000
        refresh: 2592000000

gateway:
    ip: 172.30.1.6
