
spring:
  application:
    name: user-service

server:
  # Random Port 번호를 부여하기 위해 0번 포트를 사용하도록 설정
  port: 0

eureka:

  instance:

    # instance-id 설정
    # - 기본적으로 yml파일에 있는 application name과 port 번호를 참조하여 인스터스 식별 수행
    # - random Port를 사용하기 위해 0번으로 설정하면 동일한 인스턴스로 식별하기 때문에 추가 설정 필요
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

  client:

    # Eureka 서버 등록 설정
    register-with-eureka: true

    # Eureka 서버에 등록된 인스턴스에 대한 정보 갱신 설정
    fetch-registry: true

    # Eureka 서버 위치 설정
    service-url:
      # 아래 설정한 Eureka 서버에 인스턴스 등록
      defaultZone: http://127.0.0.1:8761/eureka




