spring:
  application:
    name: user-service

server:
  port: 9001

eureka:
  client:

    # Eureka 서버 등록 설정
    register-with-eureka: true

    # Eureka 서버에 등록된 인스턴스에 대한 정보 갱신 설정
    fetch-registry: true

    # Eureka 서버 위치 설정
    service-url:
      # 아래 설정한 Eureka 서버에 인스턴스 등록
      defaultZone: http://127.0.0.1:8761/eureka




