server:
  # Random Port 번호를 부여하기 위해 0번 포트를 사용하도록 설정
  port: 0

spring:
  application:
    name: user-service

  profiles:
    active: default

  config:
    import: optional:configserver:http://localhost:8888

  # 주입할 yml 파일명 설정
  # - 기본값으로 application-name과 일치하는 yml 파일 주입
  cloud:
    config:
      name: user-service

logging:
  level:
    com.example.userservice: DEBUG
    com.example.userservice.common.client: DEBUG

management:

  # zipkin 관련 설정
  tracing:
    sampling:
      probability: 1.0

    propagation:
      consume: b3
      produce: b3_multi

  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

  # actuator 관련 설정
  endpoints:
    web:
      exposure:
        include: beans, refresh, health, httpexchanges, busrefresh, info, metrics, prometheus
