server:
  port: 8000

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:

      # route 객체 등록
      routes:
        - id: first-service             # ID 설정
          uri: http://localhost:8081    # URI 설정
          predicates:                   # 조건 설정
             - Path=/first-service/**
          filters:                      # 필터 추가
            - AddRequestHeader=first-service, first-service-request
            - AddResponseHeader=first-service, first-service-response

        - id: second-service
          uri: http://localhost:8082
          predicates:
            - Path=/second-service/**
          filters:
            - AddRequestHeader=second-service, second-service-request
            - AddResponseHeader=second-service, second-service-response

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8176/eureka

