server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          # Repository 주소
          uri: https://github.com/parkrootseok/learn-msa

          # 참조할 branch 정보 (기본값은 master)
          default-label: main