server:
  port: 8888

spring:
  application:
    name: config-service

  #  로컬에 있는 yml 파일을 가져오기 위한 설정
  #  profiles:
  #    active: native

  cloud:
    config:
      server:
        #        native:
        #          search-locations: file//${user.home}/yml 파일 위치
        git:
          # Repository 주소
          uri: https://github.com/parkrootseok/learn-msa
          # 참조할 branch 정보 (기본값은 master)
          default-label: main

# actuator 관련 설정
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

# 암호화 관련 설정
encrypt:
#  대칭키 방식
#  key: 017a3dbbaece78ce0ceb

#  비대칭키 방식
  key-store:
#    location: file://${user.home}/Desktop/programming/key-store/apiEncryptionKey.jks
    location: file:/apiEncryptionKey.jks
    password: test1234
    alias: apiEncryptionKey
